### ISSUE TITLE
Apply role/group-based authorizations to support Eos actions in prod

### ISSUE THREAD

**Issue by williewheeler** [ExpediaDotCom/seiso-ui#140]
**Problem.** To activate Eos actions in production, we need to support authorization based on both role and group.

**Acceptance criteria.** Turn on production actions, and allow only authorized users to perform them.

**Technical approach.** Roles should be collections of permissions that we apply to decide whether to authorize the action in question. Groups will usually be groups associated with the service in question. We need to fill in the authorization model here before undertaking the work.

**Comment by imccunn** [comment]
Done.
