### ISSUE TITLE
UI Page Navigation Vanished?

### ISSUE THREAD

**Issue by brownc** [ExpediaDotCom/seiso-ui#255]
We've noticed in the latest prod release, that for example if we have 2 disabled servers, and 58 MI servers (total 60) we can only see the first 50 entries listed.

This is when looking at the Service Instance overview page, where anything not Healthy/InRotation shows up.

There are no longer any page navigators - so we can't browse all of the data.  I have screenshots to illustrate.

Can someone check the code and validate status here - as this is a real pain when running deployments when you can't see everything on the UI.

Thanks!

/C.

**Comment by imccunn** [comment]
**Acceptance Criteria**

Put the pagination mechanism back on the node alerts pane on the service instance details page.

**Comment by imccunn** [comment]
Done. See #260
