### ISSUE TITLE
Use ng-annotate for dependency injection

### ISSUE THREAD

**Issue by williewheeler** [ExpediaDotCom/seiso-ui#5]
This DRYs up the injections a bit. Instead of

    dataService.$inject = ['$http', '$log'];
    function dataService($http, $log) { ... }

we can do this:

    /* @ngInject */
    function dataService($http, $log) { ... }

See https://github.com/olov/ng-annotate

**Comment by imccunn** [comment]
All controllers should now have the annotation in place. If not all, most of them. If we find any remaining manual injections we can add the annotations as we go.
