### ISSUE TITLE
Home page is limited to 300 services

### ISSUE THREAD

**Issue by imccunn** [ExpediaDotCom/seiso-ui#60]
"There are different options here. We could load all services, or make the individual service groups be AJAX calls to load the services on a per group basis. But the home page shouldn't be inherently tied to 300 services."

**Comment by williewheeler** [comment]
I've moved this into 3.0.0.RELEASE because we're going to be coming up on 300 services pretty soon. Especially with the seiso-import_aws work.

**Comment by imccunn** [comment]
This partially addressed. Right now the home page will load the names of all service groups but will only load the services for each group when a service group is opened/collapsed.

The next thing we'll want to address is being able to load more than 300 services per group by some additional call to grab the next page of services.

**Comment by williewheeler** [comment]
Thanks Ian. This is an acceptable solution for the time being. Closing the ticket.
